site_name: 爱吃卤菜
site_url: https://www.anycastol.com   # 你的网站地址（可选）
repo_url: https://github.com/auto007/mkdocs.git   # GitHub 仓库地址（可选）

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

plugins:
  - search
  - minify:               # 压缩 HTML/CSS/JS
      minify_html: true
      minify_js: true
      minify_css: true
  # - redirects:            # 设置页面跳转
  #     redirect_maps:
  #       'old-page.md': 'new-page.md'
  #       'guide/intro.md': 'tutorial/getting-started.md'

nav:
  - 首页: index.md
  - k8s:
    - 文件存储块存储对象存储区别: k8s/文件存储块存储对象存储区别.md
    - 无状态服务和有状态服务的区别: k8s/无状态服务和有状态服务的区别.md
    - StatefulSet域名解析: k8s/StatefulSet域名解析.md
    - StatefulSet之redis主从: k8s/StatefulSet之redis主从.md
    - NFS提供StorageClass: k8s/NFS提供StorageClass.md
    - StatefulSet之mysql: k8s/StatefulSet之mysql.md
    - HeadlessService和service区别: k8s/HeadlessService和service区别.md
    - 测试镜像: k8s/测试镜像.md
    - 什么情况下需要手动创建endpoint: k8s/什么情况下需要手动创建endpoint.md
    - pv与pvc: k8s/pv与pvc.md
    - 污点和容忍: k8s/污点和容忍.md
    - 污点和容忍与nodeselector区别: k8s/污点和容忍与nodeselector区别.md
    - affinity亲和性: k8s/affinity亲和性.md
    - LimitRange: k8s/LimitRange.md
    - ResourceQuota: k8s/ResourceQuota.md
    - LimitRange和ResourceQuota联合使用: k8s/LimitRange和ResourceQuota联合使用.md
    - StorageClass使用的场景: k8s/StorageClass使用的场景.md 
    - prometheus: k8s/prometheus.md
    - prometheus监控mysql: k8s/prometheus监控mysql.md
  - linux:
    - 常用: linux/常用.md
    - 内核参数提升网络传输速度: linux/内核参数提升网络传输速度.md
    - curl参数: linux/curl参数.md
    - dig命令: linux/dig命令.md
    - Rocky9安装Podman: linux/Rocky9安装Podman.md
    - dockerfile里CMD和ENTRYPOINT区别: linux/dockerfile里CMD和ENTRYPOINT区别.md
  - 云技术:
    - vps和云主机区别: 云技术/vps和云主机区别.md
  - 数据库:
    - mysql: 数据库/mysql.md
  - 生活相关:
    - 贷款利息: 生活相关/贷款利息.md
    - 车贷: 生活相关/车贷.md
    
    
  # - 教程:
  #     - 快速开始: tutorial/getting-started.md
  #     - 进阶指南: tutorial/advanced.md


